### ISSUE TITLE
nimlime doesn't syntax highlight nimble files

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/NimLime#108]
(unless one manually selects "open all current extension as ... nim, which is not the correct way; it should be automatic, and also be nimble specific (even if it defaults to nim for now) to account for potential differences bw nim and nimble)

## related
* [syntax highlight of nims, nim.cfg, nimble files broken on github, highlight, sublimetext - Nim forum](https://forum.nim-lang.org/t/4307#26806)

**Comment by AmjadHD** [comment]
This was fixed by #126.
