### ISSUE TITLE
Problems using program in Sublime terminal

### ISSUE THREAD

**Issue by ghost** [nim-lang/NimLime#132]
When I build this small prog in Sublime:
`echo "What's your name? "
var name: string = readLine(stdin)
echo "Hi, ", name, "!"`
my name is asked on (Sublime) terminal; when I type one and enter, nothing seems to happen.
Adding:
`flushFile(stdout)`
doesn't help.
Somehow the program is stalled ...

The code shown first works OK in a native terminal (cmdprompt).

**Comment by AmjadHD** [comment]
Sublime text doesn't have a builtin interactive terminal.
Watch this video on how to set up [Terminus](packagecontrol.io/packages/Terminus):
https://www.youtube.com/watch?v=etIJMVIvVgg
