### ISSUE TITLE
move this repo to nim-lang/NimLime ?

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/NimLime#154]
the issues are piling up, last commit was 2y ago and IMO there could be more reviewers, PRs and bug fixes if this repo were migrated to nim-lang/NimLime @Varriount what do you think?

github linguist submodule would also have to be udated accordingly (eg see also https://github.com/github/linguist/pull/5306)

**Comment by onionhammer** [comment]
I'm in favor of this since I have no time to continue maintaining it. We should be looking for new maintainers if varriount is also unable to maintain

**Comment by timotheecour** [comment]
let's followup in https://github.com/nim-lang/RFCs/issues/365; we need someone with sufficient priviledge to transfer issues/PR's to https://github.com/nim-lang/RFCs/issues/365
