### ISSUE TITLE
Split The repo to github and sublime branches

### ISSUE THREAD

**Issue by AmjadHD** [nim-lang/NimLime#160]
We can't rely on the fact that ST ignores a `tmLanguage` grammar file when a `sublime-syntax` file with the same name is provided, because we can't modify or test them.
The solution is to create 2 branches one for Sublime Text (and Merge) and point Package Control to it.
The other is for github and point linguist to it.

**Comment by AmjadHD** [comment]
@Varriount.

**Comment by AmjadHD** [comment]
@Varriount can you comment on this ?

**Comment by Varriount** [comment]
This is why I wanted to stick with the older `tmLanguage` grammar - having two branches of the language highlighting code invariably means that one will become out of date with the other.

**Comment by AmjadHD** [comment]
You can make the github branch the main one, so that it doesn't lag behind despite the fact that there isn't much left to add to the grammar anyway.
I'm willing to maintain both grammars.

**Comment by AmjadHD** [comment]
Also, Is there a need for all the python code ? it didn't work for me and I never used it.

**Comment by AmjadHD** [comment]
@Varriount.

**Comment by AmjadHD** [comment]
@Varriount, I need your comment on this.

**Comment by Varriount** [comment]
@AmjadHD No, I don't like the idea of placing the GitHub-specific code into a separate branch. It makes it too easy to only partially implement updates/fixes.
