### ISSUE TITLE
Update the plugin's metadata on Package Control

### ISSUE THREAD

**Issue by AmjadHD** [nim-lang/NimLime#181]
* [x] [Rename](https://packagecontrol.io/docs/renaming_a_package) to "Nim".
* [x] Update the description ("Super Nim Plugin for Sublime Text 2/3").
* [x] Update labels.

**Comment by AmjadHD** [comment]
ping @Varriount.

**Comment by AmjadHD** [comment]
ping @Varriount.

**Comment by AmjadHD** [comment]
ping @Varriount.

**Comment by AmjadHD** [comment]
Can you respond @Varriount ?

**Comment by AmjadHD** [comment]
@Araq, this has been open for 7 months now!
Should I go ahead with https://github.com/wbond/package_control_channel/pull/8815 ?
Also I need the description to be updated to something like "The official Nim programming language plugin for Sublime Text".

**Comment by Araq** [comment]
Ok, what do you want me to do?

**Comment by AmjadHD** [comment]
> Should I go ahead with https://github.com/wbond/package_control_channel/pull/8815 ?

Say yes.

**Comment by AmjadHD** [comment]
Done.
