### ISSUE TITLE
Weird highlights

### ISSUE THREAD

**Issue by georgelemon** [nim-lang/NimLime#182]
Words like `find`, `contains` should not be highlighted. Maybe there are more like this.

![Screenshot from 2023-09-27 07-48-53](https://github.com/nim-lang/NimLime/assets/1230420/25f60cb1-c0e7-4260-ad23-30f8f18b2506)

Also, `echo` used to be part of `keyword.control`.

**Comment by AmjadHD** [comment]
They are highlighted because they are builtins i.e available in the system module.

**Comment by georgelemon** [comment]
Alright. Then, `find` in that context is a valid name for a package so it should not be highlighted. LSP can print info about std libs. Complicating the syntax with useless regex is too much (never used LSP).

**Comment by Araq** [comment]
> They are highlighted because they are builtins i.e available in the system module.

That set keeps changing and depends on the used mode too, some things are not supported by `nim js`, for example. Also, the highlighter never knows if the "builtin" symbol wasn't shadowed. "builtin" is not a useful category for Nim and should be abolished.

**Comment by AmjadHD** [comment]
> That set keeps changing and depends on the used mode too, some things are not supported by `nim js`, for example. Also, the highlighter never knows if the "builtin" symbol wasn't shadowed.

It doesn't matter, it's not meant to be an exhaustive list it's just to give a somewhat good idea about the builtin namespace.
Many don't use IDEs (and LSP for that matter) removing builtin highlighting means a bad experience for them.
I try to follow the norms of each tool, Sublime syntax definitions highlight builtins so I do, Github's don't so I don't.

**Comment by Araq** [comment]
Wrong highlighting that does not reflect reality does not help anybody. Highlighting in general is overdone with too many different colors that nobody understands anyway. The distinction between keywords and non-keywords is all that matters. Then you also highlight string literals and comments different and you covered 100% of what is useful.
