### ISSUE TITLE
Install LSP by default

### ISSUE THREAD

**Issue by omentic** [nim-lang/NimLime#185]
With tooling being stabilized, NimLime should take cues from https://packagecontrol.io/packages/LSP-rust-analyzer and install an LSP configuration for `nimlangserver` by default.

**Comment by AmjadHD** [comment]
There is now an [LSP plugin](https://github.com/AmjadHD/LSP-nimlangserver). It's not on Package Control yet.
I don't know if they should be merged to one plugin, but one certainly can recommend the other.
