### ISSUE TITLE
Incorrect highlighting for type suffixes

### ISSUE THREAD

**Issue by dom96** [nim-lang/NimLime#43]
https://github.com/nim-lang/Nim/blob/devel/compiler/semfold.nim#L309

**Comment by tajmone** [comment]
I'm not sure id @dom96 is referring to the same thing, but float literals with the `'f` (without bitness) or `'d` suffix are parsed incorrectly, where the `'` is seen as a single-quote string:

```nim
var
  f1 = 0.0'f       # float32 (not handled correctly)
  f2 = 0.0'd       # float64 (not handled correctly)
  f3 = 0.0'f32     # float32
  f4 = 0.0'f64     # float64
  f5 = 0.0'f128    # float128
```

In ST it shows just like in the preview here on GitHub, with the code from `f` up to `'d` (excluded) in red (as if it was a char literal with more than one char, shown as "invalid").

From the documentation it seems that they should be supported:

- https://nim-lang.org/docs/manual.html#lexical-analysis-numerical-constants

I'm experiencing the same issue on [Visual Code Studio](https://github.com/pragmagic/vscode-nim), so I wonder if it's a bug or not.

**Comment by tajmone** [comment]
I've also opened a similar Issue report for vscode-nim:

https://github.com/pragmagic/vscode-nim/issues/111
