### ISSUE TITLE
Compiler flags for error/warning checks.

### ISSUE THREAD

**Issue by hakanderyal** [nim-lang/NimLime#75]
When using `--gc:stack`, `system.nim` imports/exports `MemRegion` type. (not exported with other gc's)

When using it, nimlime marks it's usage as not defined error, which I'm guessing it checks the file with standard gc.

Is there any way to make error checking aware of compiler flags, or some other way to make nimlime ignore this errors?

**Comment by Varriount** [comment]
Hm. There are two ways this could be dealt with, neither implemented at this time. Either a setting could be added that allows passing additional arguments to the `nim check` command (which is executed as a subprocess) or an ignore_regex setting could be added to allow filtering the `Nim check` output.
