### ISSUE TITLE
Only lowercase reserved words are highlighted.

### ISSUE THREAD

**Issue by mooskagh** [nim-lang/NimLime#87]
Reserved words in NimLime are only colored when they are lowercase: var, proc, import, etc.

When they are written capitalized: VAR or Var or ProC, they are not recognised as reserved words.
Same for inserting underscores, i.e. Va_R, pr_oc, etc, although I'm not sure whether anyone would spell them that way ever.

**Comment by AmjadHD** [comment]
Accounting for all the possible forms a keyword or an identifier in general can take is not worth it.
Note: `VAR`, `Var` and `Va_R` are not identical to `var`, same with `ProC` because the first letter's case is different.

**Comment by mooskagh** [comment]
It's long time since I touched nim..,

but isn't nim case insensitive, including reserved words?

**Comment by AmjadHD** [comment]
It's partially case-insensitive, the first character is case-sensitive.
