### ISSUE TITLE
Add additional argument support to commands

### ISSUE THREAD

**Issue by cryptogun** [nim-lang/NimLime#89]
Nim compiles and runs well. Yet NimLime complains a lot. Here's the code:
```nim
# Code from: https://github.com/nim-lang/Nim/issues/2257#issuecomment-87856997
import threadpool

const ch_max:int = 3

var channels: array[1..ch_max, Channel[string]] # TChannel deplicated.

proc consumer(ix : int) {.thread.} =
  echo "received: " & channels[ix].recv()

proc main =

  for ix in countup(1,ch_max):
    echo "opening: " & $ix & "/" & $ch_max
    channels[ix].open()

  for ix in countup(1,ch_max):
    echo "spawning: " & $ix & "/" & $ch_max
    spawn consumer(ix)

  for ix in countup(1,ch_max):
    echo "sending: " & $ix & "/" & $ch_max
    channels[ix].send("channel recv " & $ix)

  sync()
  echo "synced"

  for ix in countup(1,ch_max): channels[ix].close()

when isMainModule:
  echo "<<begin>>"
  main()
  echo "<<end>>"

```

And this Warning: `Not GC-safe` with code blow. No such warning using `nim c -r`. That scares. 
```nim
type Man = ref object of RootObj
method run(this: Man) {.base.} =
    echo "running"
var bob = new Man
bob.run()
```
`Nim Compiler Version 0.17.2 (2017-09-07) [Windows: amd64]`

**Comment by Varriount** [comment]
The first problem is because NimLime doesn't add `--threads:on`. This could be fixed in in NimLime by adding `--threads:on` to the code.

Your second problem can be fixed by setting the 'check.on_save.verbosity' level to 1, rather than 2. I won't change the default value, as that code isn't GC-safe in a threaded environment.

**Comment by cryptogun** [comment]
Well I'll keep it then. I though Nim fixed that problem so it didn't warn me for GC unsafe.   
As for `threads` switch, most of the time we don't need it I think. Search text for `import threadpool` and then insert switch would be better.  

Thanks and cheers :)
